// Create a user
POST http://localhost:5000/regist
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@gmail.com",
    "password": "pw",
    "confPassword": "pw"
}

###

GET http://localhost:5000/users

###

DELETE http://localhost:5000/users/84c6ceb5-359c-4f18-8667-47b47d7f6bc2

###
PATCH http://localhost:5000/users/30e29784-0c43-44dc-af4b-6ce38a01ee5b
Content-Type: application/json

{
    "name": "ame",
    "email": "test@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "daffa@gmail.com",
    "password": "pw"
}

###
GET http://localhost:5000/Me

###
DELETE http://localhost:5000/logout
