// Create a user
POST http://34.101.188.192:5000/regist
Content-Type: application/json
// contoh input data
{
    "name": "user1",
    "email": "user1@gmail.com",
    "password": "pw",
    "confPassword": "pw"
}

###
// Get all users (adminOnly)
GET http://34.101.188.192:5000/users

###
// Delete user by Id (adminOnly)
DELETEhttp://34.101.188.192:5000/users/84c6ceb5-359c-4f18-8667-47b47d7f6bc2

###
Update user by Id (adminOnly)
PATCH http://34.101.188.192:5000/users/30e29784-0c43-44dc-af4b-6ce38a01ee5b
Content-Type: application/json
// contoh input data
{
    "name": "ame",
    "email": "test@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
// login
POST http://34.101.188.192:5000/login
Content-Type: application/json

{
    "email": "daffa@gmail.com",
    "password": "pw"
}

###
// Info user yg login
GET http://34.101.188.192:5000/Me

###
// logout
DELETE http://34.101.188.192:5000/logout
